# Generated by Django 3.2 on 2022-09-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigoclase', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreEstudiante', models.CharField(max_length=40)),
                ('nombreDocente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ApellidoPaterno', models.CharField(max_length=40)),
                ('ApellidoMaterno', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.carrera')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(max_length=40)),
                ('apellidoMaterno', models.CharField(max_length=40)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.estudiante')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
    ]
